config/routes.rb
Rails.application.routes.draw do
  resources :articles

  resources :image_posts

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates :url, {
    :allow_blank => true,
    :format => URI::regexp(%w(http https)),
  }
end

app/models/image_post.rb
class ImagePost < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @article = Article.new
    @articles = Article.order('created_at DESC').paginate(:page => params[:page], :per_page => 50)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to action: 'index', notice: 'Article was successfully created.' }
        format.json { render :index, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to action: 'index', notice: 'Article was successfully updated.' }
        format.json { render :index, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :email, :title, :comment, :url, :delete_key, :photo)
    end
end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController
  before_action :set_image_post, only: [:show, :edit, :update, :destroy]

  # GET /image_posts
  # GET /image_posts.json
  def index
    @image_posts = ImagePost.all
  end

  # GET /image_posts/1
  # GET /image_posts/1.json
  def show
  end

  # GET /image_posts/new
  def new
    @image_post = ImagePost.new
  end

  # GET /image_posts/1/edit
  def edit
  end

  # POST /image_posts
  # POST /image_posts.json
  def create
    @image_post = ImagePost.new(image_post_params)

    respond_to do |format|
      if @image_post.save
        format.html { redirect_to @image_post, notice: 'Image post was successfully created.' }
        format.json { render :show, status: :created, location: @image_post }
      else
        format.html { render :new }
        format.json { render json: @image_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_posts/1
  # PATCH/PUT /image_posts/1.json
  def update
    respond_to do |format|
      if @image_post.update(image_post_params)
        format.html { redirect_to @image_post, notice: 'Image post was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_post }
      else
        format.html { render :edit }
        format.json { render json: @image_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_posts/1
  # DELETE /image_posts/1.json
  def destroy
    @image_post.destroy
    respond_to do |format|
      format.html { redirect_to image_posts_url, notice: 'Image post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_post
      @image_post = ImagePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_post_params
      params.require(:image_post).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
require 'uri'

module ArticlesHelper
  def auto_link_to(text)
    result=[]
    return result if text.blank?
    text.split("\n").each { |line|
      URI.extract(line,["http","https"]).each do |uri|
        line=link_to(uri,uri)
      end
      result.push(line)
    }
    result.join("\n")
  end
end

app/helpers/image_posts_helper.rb
module ImagePostsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "form-horizontal article" } do |f| %>

    <% if @article.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'col-md-3 control-label' %>
    <div class="col-md-9 controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'col-md-3 control-label' %>
    <div class="col-md-9 controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'col-md-3 control-label' %>
    <div class="col-md-9 controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :comment, :class => 'col-md-3 control-label' %>
    <div class="col-md-9 controls">
      <%= f.text_area :comment, :class => 'form-control' ,:rows=>6 %>
    </div>
    <%= error_span(@article[:comment]) %>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'col-md-3 control-label' %>
    <div class="col-md-9 controls">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:url]) %>
  </div>
  <div class="control-group">
    <%= f.label :delete_key, :class => 'col-md-3 control-label' %>
    <div class="col-md-9 controls">
      <%= f.password_field :delete_key, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:delete_key]) %>
  </div>
  <div class="control-group">
    <%= f.label :photo, :class => 'col-md-3 control-label' %>
    <div class="col-md-9 controls">
      <%= f.file_field :photo, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:photo]) %>
  </div>

  <div class="control-group">
    <label class="col-md-3 control-label"></label>
    <div class="col-md-9 controls">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      articles_path, :class => 'btn btn-default' %>
    </div>
   </div>

<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header text-center">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>

<div>
<%= will_paginate @articles, :renderer => BootstrapPagination::Rails %>
</div>

<% @articles.each do |article| %>

<div class="article_list well">

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= article.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= article.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= article.created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><strong><%= article.title %></strong></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= simple_format(auto_link_to(article.comment)) %></dd>
  <% if article.valid?  %>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= link_to(article.url,article.url,{:target=>"_blank"}) %></dd>
  <% end %>
  <% if article.photo.present? %>
  <dt><strong><%= model_class.human_attribute_name(:photo) %>:</strong></dt>
  <dd><%= image_tag(article.photo.url(:medium),:class=>"img-thumbnail") %></dd>
  <% end %>
</dl>
</div>

<% end %>


<div>
<%= will_paginate @articles, :renderer => BootstrapPagination::Rails %>
</div>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

app/views/image_posts/_form.html.erb
<%= form_for(@image_post) do |f| %>
  <% if @image_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image_post.errors.count, "error") %> prohibited this image_post from being saved:</h2>

      <ul>
      <% @image_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_posts/edit.html.erb
<h1>Editing Image Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @image_post %> |
<%= link_to 'Back', image_posts_path %>

app/views/image_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Image Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_posts.each do |image_post| %>
      <tr>
        <td><%= image_post.name %></td>
        <td><%= link_to 'Show', image_post %></td>
        <td><%= link_to 'Edit', edit_image_post_path(image_post) %></td>
        <td><%= link_to 'Destroy', image_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image post', new_image_post_path %>

app/views/image_posts/new.html.erb
<h1>New Image Post</h1>

<%= render 'form' %>

<%= link_to 'Back', image_posts_path %>

app/views/image_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image_post.name %>
</p>

<%= link_to 'Edit', edit_image_post_path(@image_post) %> |
<%= link_to 'Back', image_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TwitterBootstrap" %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button> 
    <%= message %>
  </div>
  <% end %> 
  <%= bootstrap_flash %>
    <div class="container">
           <%= yield %>
       <footer>
        <p>&copy; Shibacow 2015</p>
      </footer>
    </div> <!-- /container -->
</body>
</html>